id: IB4647CAF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:13:17+00:00'
last_modified: '2022-06-08T09:38:26.761496+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6400
  title: སྔགས་ཡིག་ཀློག་སྟངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2FBF:
      image_group_id: I3CN6402
      title: ''
      total_pages: 136
      order: 1
      base_file: 2FBF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
