id: P006917
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 12:30:35.599723
source_metadata:
  id: bdr:W3CN6400
  title: སྔགས་ཡིག་ཀློག་སྟངས།
  author: ''
  volumes:
    f1ac42140cd94d23b4f6b092b42c348f:
      image_group_id: I3CN6402
      title: ''
      volume_number: 1
      total_pages: 136
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
